### PR TITLE
rpm: rpmlint fixes

### PR DESCRIPTION
**Pull request by ktdreyer**
Fix some packaging issues that will arise during the Fedora packaging review.

### CODE REVIEW

**Comment by kamleshverma1** [comment]
@TimothyAsir Please review it .

**Comment by r0h4n** [comment]
Please update this PR

**Comment by ktdreyer** [comment]
@r0h4n would you please clarify specifically what you want me to do? "update this PR" is vague when there are no other comments and the CI build has passed. For example, do you want me to rebase it (I've rebased it now, just guessing).

**Comment by TimothyAsir** [comment]
:+1: looks good to me.

**Comment by ktdreyer** [comment]
@r0h4n thanks for clarifying!

**Pull request merged**
